--- #YAML:1.0
name:               Test-Simpler
version:            0.000005
abstract:           Simpler than Test::Simple; more powerful than Test::More
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:           0
    PadWalker:            0
    PPI:                  0
    Test::Builder::Module:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
